apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: clean_arch/migrate
      docker:
        dockerfile: skaffold/migrate/Dockerfile
    - image: clean_arch/api
      docker:
        dockerfile: skaffold/api/Dockerfile
deploy:
  kubectl:
    manifests:
      - skaffold/rdb/k8s/*
      - skaffold/migrate/k8s/*
      - skaffold/api/k8s/*
profiles:
  - name: rdb
    build:
      artifacts:
        - image: clean_arch/migrate
          docker:
            dockerfile: skaffold/migrate/Dockerfile
    deploy:
      kubectl:
        manifests:
          - skaffold/rdb/k8s/*
          - skaffold/migrate/k8s/*
  - name: api
    build:
      artifacts:
        - image: clean_arch/api
          docker:
            dockerfile: skaffold/api/Dockerfile
    deploy:
      kubectl:
        manifests:
          - skaffold/api/k8s/*
