apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  mysql.cnf: |
    [mysqld]
    character-set-server=utf8
    skip_ssl
    general_log=1
    log_output=TABLE

    [client]
    default-character-set=utf8